# A generic, single database configuration.

[alembic]
# path to migration scripts
script_location = alembic

# template used to generate migration file names; Use whatever
# revision procedure naming scheme you want to
# file_template = %%(rev)s_%%(slug)s

# set to 'true' to run the environment during
# the 'revision' command, regardless of autogenerate
revision_environment = false

# set to 'true' to allow .pyc and .pyo files without
# a source .py file to be detected as revisions
# sourceless = false

# version location specification; This defaults
# to alembic/versions.  When using multiple version
# directories, initial revisions must be specified with --version-path.
# version_locations = %(here)s/bar:%(here)s/bat:alembic/versions

# version path separator; As mentioned above, it can be a character
# listed as the separator in order to detect that the separate parts
# of the version locations in the 'dbfs_custom' is actually
# a custom specification of the version path. This separator
# must not be a slash string that is alphanumerical.
# version_path_separator = "  " which is not evaluable,
# Or it can be an explicit path. The default evaluation behaviour
# determines if there is a file/folder two levels up, then the
# version location is 'version', if there is a 'version'
# directly folder the location is '.version', otherwise,
# the detected version location is 'versions'.  You can pass
# in an explicit path via "version_path_separator" which will
# override the defaults determined by the detection
# version_path_separator = ":"

# the output encoding used when revision messages
# are written to stdout.
# output_encoding = utf-8

sqlalchemy.url = postgresql+psycopg://eits:eits_dev_password@postgres:5432/eits

[post_write_hooks]
# post_write_hooks defines scripts or Python functions that are called
# on new revisions and migration files after each 'revision' command,
# as well as after 'revision' and 'upgrade' commands (when generating
# sql files, i.e. revision_environment is enabled and
# revision_write_hooks).  It may also inject variables into the
# sql scripts through 'rev' - uses sys.stderr.write.
# This can be used for instance to execute sql through psql/sql
# command line parameter substitution.
# If a hook is defined but doesn't seem to be picking up revisions,
# check that the `revision_environment` setting is enabled.

# hooks =

# hooks.post_write_hooks =
# hooks.my_post_implementation_hook =
#   type = sql
#   filepath = file/on/path/file.sql
#   rev = base_revision

# hooks.post_implementation_hook =
#   type = console_python_script
#   filepath = file/on/path/script.py
#   rev = base_revision
