"""add division_id to business_processes and memberships

Revision ID: 53daea59fbb8
Revises: 9f13a6c8d445
Create Date: 2026-05-09 12:49:06.011686

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '53daea59fbb8'
down_revision: Union[str, None] = '9f13a6c8d445'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('business_processes', sa.Column('division_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_business_processes_division_id'), 'business_processes', ['division_id'], unique=False)
    op.create_foreign_key(None, 'business_processes', 'divisions', ['division_id'], ['id'])
    op.add_column('memberships', sa.Column('division_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_memberships_division_id'), 'memberships', ['division_id'], unique=False)
    op.create_foreign_key(None, 'memberships', 'divisions', ['division_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'memberships', type_='foreignkey')
    op.drop_index(op.f('ix_memberships_division_id'), table_name='memberships')
    op.drop_column('memberships', 'division_id')
    op.drop_constraint(None, 'business_processes', type_='foreignkey')
    op.drop_index(op.f('ix_business_processes_division_id'), table_name='business_processes')
    op.drop_column('business_processes', 'division_id')
    # ### end Alembic commands ###