"""add is_active to alerts

Revision ID: 59ba4f69c258
Revises: f1961e49913e
Create Date: 2026-05-09 11:20:01.678883

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '59ba4f69c258'
down_revision: Union[str, None] = 'f1961e49913e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Add column as nullable first
    op.add_column('alerts', sa.Column('is_active', sa.String(length=10), nullable=True))
    # Update existing rows to "true"
    op.execute("UPDATE alerts SET is_active = 'true' WHERE is_active IS NULL")
    # Alter to NOT NULL
    op.alter_column('alerts', 'is_active', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('alerts', 'is_active')
    # ### end Alembic commands ###