"""add division model and tenant company fields

Revision ID: 9f13a6c8d445
Revises: 59ba4f69c258
Create Date: 2026-05-09 12:47:15.730552

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9f13a6c8d445'
down_revision: Union[str, None] = '59ba4f69c258'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('divisions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('parent_division_id', sa.UUID(), nullable=True),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('head_user_id', sa.UUID(), nullable=True),
    sa.Column('is_active', sa.String(length=10), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['head_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['parent_division_id'], ['divisions.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_divisions_tenant_id'), 'divisions', ['tenant_id'], unique=False)
    op.add_column('tenants', sa.Column('legal_form', sa.String(length=50), nullable=True))
    op.add_column('tenants', sa.Column('registration_date', sa.Date(), nullable=True))
    op.add_column('tenants', sa.Column('status', sa.String(length=50), nullable=True))
    op.add_column('tenants', sa.Column('registered_address', sa.Text(), nullable=True))
    op.add_column('tenants', sa.Column('contact_address', sa.Text(), nullable=True))
    op.add_column('tenants', sa.Column('phone', sa.String(length=50), nullable=True))
    op.add_column('tenants', sa.Column('email', sa.String(length=255), nullable=True))
    op.add_column('tenants', sa.Column('website', sa.String(length=255), nullable=True))
    op.add_column('tenants', sa.Column('share_capital', sa.Numeric(precision=15, scale=2), nullable=True))
    op.add_column('tenants', sa.Column('nace_codes', postgresql.JSON(astext_type=sa.Text()), nullable=True))
    op.add_column('tenants', sa.Column('company_type', sa.String(length=20), nullable=True))
    op.add_column('tenants', sa.Column('parent_company_id', sa.UUID(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tenants', 'parent_company_id')
    op.drop_column('tenants', 'company_type')
    op.drop_column('tenants', 'nace_codes')
    op.drop_column('tenants', 'share_capital')
    op.drop_column('tenants', 'website')
    op.drop_column('tenants', 'email')
    op.drop_column('tenants', 'phone')
    op.drop_column('tenants', 'contact_address')
    op.drop_column('tenants', 'registered_address')
    op.drop_column('tenants', 'status')
    op.drop_column('tenants', 'registration_date')
    op.drop_column('tenants', 'legal_form')
    op.drop_index(op.f('ix_divisions_tenant_id'), table_name='divisions')
    op.drop_table('divisions')
    # ### end Alembic commands ###