"""create alerts table

Revision ID: f1961e49913e
Revises: add_permissions_role_permissions
Create Date: 2026-05-09 11:13:47.502832

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f1961e49913e'
down_revision: Union[str, None] = 'add_permissions_role_permissions'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alerts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('level', sa.Enum('info', 'warning', 'error', 'success', name='alert_level'), nullable=False),
    sa.Column('target_role', sa.Enum('admin', 'ism', 'all', name='alert_target_role'), nullable=False),
    sa.Column('is_read', sa.String(length=10), nullable=False),
    sa.Column('read_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default='now()', nullable=True),
    sa.Column('link', sa.String(length=255), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('alerts')
    # ### end Alembic commands ###